name: Test y verificación del sistema RAG

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Verificar sintaxis Python
      run: |
        python -m py_compile app.py ingestador.py
        
    - name: Crear directorios necesarios
      run: |
        mkdir -p documentos
        mkdir -p base_datos
        
    - name: Mostrar estructura de archivos
      run: |
        ls -la
        
    - name: Verificar README
      run: |
        if [ ! -f README.md ]; then
          echo "README.md no encontrado"
          exit 1
        fi 